// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorkDorkMain.Models;

#nullable disable

namespace StorkDork.Migrations.StorkDorkDb
{
    [DbContext(typeof(StorkDorkDbContext))]
    [Migration("20250425221538_AddDisplayNameToSdUser")]
    partial class AddDisplayNameToSdUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorkDorkMain.Models.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamilyCommonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FamilyScientificName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Order")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Range")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReportAs")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpeciesCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Bird__3214EC27152FA685");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SdUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3214EC2791C5CD06");

                    b.HasIndex("SdUserId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("StorkDorkMain.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirdId")
                        .HasColumnType("int");

                    b.Property<int?>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<bool?>("Sighted")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3214EC27391E9E0F");

                    b.HasIndex("BirdId");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("StorkDorkMain.Models.SdUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspNetIdentityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__SDUser__3214EC27D4DAB424");

                    b.ToTable("SDUser", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirdId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("SdUserId")
                        .HasColumnType("int");

                    b.Property<string>("Subdivision")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Sighting__3214EC27BEAC21ED");

                    b.HasIndex("BirdId");

                    b.HasIndex("SdUserId");

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("StorkDorkMain.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnonymousSightings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SdUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_UserSettings_3214EC27");

                    b.HasIndex("SdUserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", "SdUser")
                        .WithMany()
                        .HasForeignKey("SdUserId");

                    b.Navigation("SdUser");
                });

            modelBuilder.Entity("StorkDorkMain.Models.ChecklistItem", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("BirdId")
                        .HasConstraintName("FK_ChecklistItem_Bird");

                    b.HasOne("StorkDorkMain.Models.Checklist", "Checklist")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistId")
                        .HasConstraintName("FK_ChecklistItem_Checklist");

                    b.Navigation("Bird");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Sighting", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany("Sightings")
                        .HasForeignKey("BirdId")
                        .HasConstraintName("FK_Sighting_Bird");

                    b.HasOne("StorkDorkMain.Models.SdUser", "SdUser")
                        .WithMany()
                        .HasForeignKey("SdUserId");

                    b.Navigation("Bird");

                    b.Navigation("SdUser");
                });

            modelBuilder.Entity("StorkDorkMain.Models.UserSettings", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", "SdUser")
                        .WithOne("UserSettings")
                        .HasForeignKey("StorkDorkMain.Models.UserSettings", "SdUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SdUser");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Bird", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("StorkDorkMain.Models.SdUser", b =>
                {
                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
