// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorkDorkMain.Data;

#nullable disable

namespace StorkDork.Migrations.StorkDorkDb
{
    [DbContext(typeof(StorkDorkDbContext))]
    [Migration("20250513082540_AddBirdPhotos")]
    partial class AddBirdPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorkDorkMain.Models.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamilyCommonName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamilyScientificName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Range")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReportAs")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpeciesCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Bird__3214EC27152FA685");

                    b.ToTable("Bird", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.BirdPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BirdId");

                    b.ToTable("BirdPhoto");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SdUserId")
                        .HasColumnType("int")
                        .HasColumnName("SDUserID");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3214EC271BFFB94F");

                    b.HasIndex("SdUserId");

                    b.ToTable("Checklist", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirdId")
                        .HasColumnType("int")
                        .HasColumnName("BirdID");

                    b.Property<int?>("ChecklistId")
                        .HasColumnType("int")
                        .HasColumnName("ChecklistID");

                    b.Property<bool?>("Sighted")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3214EC27AEE131D7");

                    b.HasIndex("BirdId");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistItem", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhotosContributed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SDUserId")
                        .HasColumnType("int")
                        .HasColumnName("SDUserID");

                    b.Property<int>("SightingsMade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Milestone__3214EC27");

                    b.ToTable("Milestone");
                });

            modelBuilder.Entity("StorkDorkMain.Models.ModeratedContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModeratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("int");

                    b.Property<string>("ModeratorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("ModeratedContent", (string)null);

                    b.HasDiscriminator<string>("ContentType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StorkDorkMain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RelatedUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Notifications");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.SdUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspNetIdentityId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AspNetIdentityID");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__SDUser__3214EC277D9B2DC9");

                    b.ToTable("SDUser", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirdId")
                        .HasColumnType("int")
                        .HasColumnName("BirdID");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(8, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("SdUserId")
                        .HasColumnType("int")
                        .HasColumnName("SDUserID");

                    b.Property<string>("Subdivision")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Sighting__3214EC2734C618BE");

                    b.HasIndex("BirdId");

                    b.HasIndex("SdUserId");

                    b.ToTable("Sighting", (string)null);
                });

            modelBuilder.Entity("StorkDorkMain.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnonymousSightings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SdUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_UserSettings_3214EC27");

                    b.HasIndex("SdUserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("StorkDorkMain.Models.BirdPhotoSubmission", b =>
                {
                    b.HasBaseType("StorkDorkMain.Models.ModeratedContent");

                    b.Property<int>("BirdId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("BirdId");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Caption");

                    b.Property<string>("PhotoContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhotoContentType");

                    b.Property<byte[]>("PhotoData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PhotoData");

                    b.HasIndex("BirdId");

                    b.HasDiscriminator().HasValue("BirdPhoto");
                });

            modelBuilder.Entity("StorkDorkMain.Models.RangeSubmission", b =>
                {
                    b.HasBaseType("StorkDorkMain.Models.ModeratedContent");

                    b.Property<int>("BirdId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("BirdId");

                    b.Property<string>("RangeDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SubmissionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasIndex("BirdId");

                    b.HasDiscriminator().HasValue("BirdRange");
                });

            modelBuilder.Entity("StorkDorkMain.Models.BirdPhoto", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany("Photos")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", "SdUser")
                        .WithMany("Checklists")
                        .HasForeignKey("SdUserId");

                    b.Navigation("SdUser");
                });

            modelBuilder.Entity("StorkDorkMain.Models.ChecklistItem", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("BirdId")
                        .HasConstraintName("FK_ChecklistItem_Bird");

                    b.HasOne("StorkDorkMain.Models.Checklist", "Checklist")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistId")
                        .HasConstraintName("FK_ChecklistItem_Checklist");

                    b.Navigation("Bird");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("StorkDorkMain.Models.ModeratedContent", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StorkDorkMain.Models.SdUser", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Moderator");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Notification", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Sighting", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany("Sightings")
                        .HasForeignKey("BirdId")
                        .HasConstraintName("FK_Sighting_Bird");

                    b.HasOne("StorkDorkMain.Models.SdUser", "SdUser")
                        .WithMany("Sightings")
                        .HasForeignKey("SdUserId")
                        .HasConstraintName("FK_Sighting_SDUser");

                    b.Navigation("Bird");

                    b.Navigation("SdUser");
                });

            modelBuilder.Entity("StorkDorkMain.Models.UserSettings", b =>
                {
                    b.HasOne("StorkDorkMain.Models.SdUser", null)
                        .WithOne("UserSettings")
                        .HasForeignKey("StorkDorkMain.Models.UserSettings", "SdUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StorkDorkMain.Models.BirdPhotoSubmission", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("StorkDorkMain.Models.RangeSubmission", b =>
                {
                    b.HasOne("StorkDorkMain.Models.Bird", "Bird")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Bird", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Photos");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("StorkDorkMain.Models.Checklist", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("StorkDorkMain.Models.SdUser", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Sightings");

                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
